### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by leper** [s0600204/0ad-structree-mod#6]
Our scripts are gpl licensed, so it would be nice if this mod could be licensed under the same terms (mostly because I want to include this in the main game).

**Comment by leper** [comment]
Just read the change a bit closer, could you make it GPL2+ and readd the CC-BY-SA3.0 part too (at least I would consider the gui xmls to be under the latter)? Thank you!

**Comment by s0600204** [comment]
Better?

**Comment by leper** [comment]
Yes, thank you!
